use_frameworks!

platform :ios, '8.0'

target 'GSWCategory_Example' do
  pod 'GSWCategory', :path => '../'

  target 'GSWCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
